// Fix: We import the library as a whole object to ensure all converters are available
const curlconverter = require('curlconverter');

exports.handler = async (event, context) => {
    if (event.httpMethod !== "POST") {
        return { statusCode: 405, body: "Method Not Allowed" };
    }

    try {
        const data = JSON.parse(event.body);
        const { curlInput, targetLang } = data;

        if (!curlInput || !targetLang) {
            return { statusCode: 400, body: JSON.stringify({ error: "Missing cURL input or target language." }) };
        }

        let generatedSnippet = "";

        // --- REAL CONVERSION LOGIC USING curlconverter ---
        if (targetLang === 'python') {
            // Using the 'toPython' function from the imported object
            generatedSnippet = curlconverter.toPython(curlInput);
            
            // Add a small header for clarity
            generatedSnippet = `# Generated by Snippet Genie\n# Target: Python Requests\n\n` + generatedSnippet;

        } else if (targetLang === 'nodejs') {
            generatedSnippet = `// Node.js support is coming soon! For now, please select Python.`;
        } else if (targetLang === 'go') {
            generatedSnippet = `// Go support is coming soon! For now, please select Python.`;
        } else {
             generatedSnippet = `Error: Unsupported language selected.`;
        }
        
        // Final Response to the client (app.js)
        return {
            statusCode: 200,
            body: JSON.stringify({ snippet: generatedSnippet })
        };

    } catch (error) {
        // If curlconverter fails to parse the cURL (Invalid syntax)
        console.error("Conversion/Parsing Error:", error);
        return {
            statusCode: 422,
            body: JSON.stringify({ 
                error: `Could not parse the cURL command. Check syntax. Details: ${error.message}`
            })
        };
    }
};