// app.js (SIMPLIFIED FINAL VERSION - GLOBALLY LOADED VIA INDEX.HTML)

// Note: The curlconverter library is loaded globally in index.html,
// so we don't need 'await import' or 'let curlConverterModule'.

document.addEventListener('DOMContentLoaded', () => {
    const convertButton = document.getElementById('convert-button');
    const inputCode = document.getElementById('input-code');
    const outputSnippet = document.getElementById('output-snippet');
    const outputLanguage = document.getElementById('output-language');
    const copyButton = document.getElementById('copy-button');
    const loadingIndicator = document.getElementById('loading-indicator');

    // --- Core Conversion Logic ---
    convertButton.addEventListener('click', () => { // Removed 'async'
        const curlInput = inputCode.value.trim();
        const targetLang = outputLanguage.value;

        if (!curlInput) {
            alert("Please paste your cURL command or code here.");
            return;
        }

        outputSnippet.textContent = 'Converting...';
        loadingIndicator.style.display = 'block';

        try {
            // Check if the global variable is available (safety check)
            if (typeof curlconverter === 'undefined') {
                outputSnippet.textContent = `CRITICAL ERROR: curlconverter library did not load. Please Hard Refresh.`;
                return;
            }

            let generatedSnippet = "";

            // --- REAL CONVERSION LOGIC USING GLOBAL curlconverter ---
            if (targetLang === 'python') {
                // Use the global variable directly
                generatedSnippet = curlconverter.toPython(curlInput); 
                generatedSnippet = `# Generated by Snippet Genie\n# Target: Python Requests (Client-Side - Stable)\n\n` + generatedSnippet;
            
            } else if (targetLang === 'nodejs') {
                 // Engagement message for future feature
                 generatedSnippet = `// ✨ Node.js Support Coming Soon! ✨\n// This feature is currently under active development and will be released next week!\n// For now, please enjoy the fast and accurate Python conversion.`;
            
            } else if (targetLang === 'go') {
                 // Engagement message for future feature
                 generatedSnippet = `// Go Support Coming Soon!\n// We prioritize Node.js, but Go support will follow shortly after.\n// Please check back soon!`;
            } else {
                 generatedSnippet = `Error: Unsupported language selected.`;
            }
            
            outputSnippet.textContent = generatedSnippet;

        } catch (error) {
            console.error("Client-side Conversion Error:", error);
            outputSnippet.textContent = `Error: Could not parse the cURL command. Check syntax. Details: ${error.message}.`;
            alert(`Error during conversion: ${error.message}`);
        } finally {
             loadingIndicator.style.display = 'none';
        }
    });

    // --- Copy Button Logic (Remains the same) ---
    copyButton.addEventListener('click', () => {
        const textToCopy = outputSnippet.textContent;
        navigator.clipboard.writeText(textToCopy).then(() => {
            copyButton.textContent = 'Copied!';
            setTimeout(() => {
                copyButton.textContent = 'Copy Code';
            }, 2000);
        }).catch(err => {
            console.error('Could not copy text: ', err);
            alert('Failed to copy text. Please copy manually.');
        });
    });
});