// app.js (FINAL VERSION - CLIENT-SIDE CONVERSION)

// 1. DYNAMIC IMPORT: We will import the library inside the conversion function
// to ensure it only loads when needed.
let curlConverterModule = null;

document.addEventListener('DOMContentLoaded', () => {
    const convertButton = document.getElementById('convert-button');
    const inputCode = document.getElementById('input-code');
    const outputSnippet = document.getElementById('output-snippet');
    const outputLanguage = document.getElementById('output-language');
    const copyButton = document.getElementById('copy-button');
    const loadingIndicator = document.getElementById('loading-indicator');

    // --- Core Conversion Logic ---
    convertButton.addEventListener('click', async () => {
        const curlInput = inputCode.value.trim();
        const targetLang = outputLanguage.value;

        if (!curlInput) {
            alert("Please paste your cURL command or code here.");
            return;
        }

        outputSnippet.textContent = 'Loading converter module...';
        loadingIndicator.style.display = 'block';

        try {
            // Check if the module is loaded, if not, dynamically load it from esm.sh!
            if (!curlConverterModule) {
                // FIX: Using esm.sh CDN for reliable ES Module loading in browsers (NO NETLIFY CREDIT SPENT!)
                const module = await import('curlconverter');
                curlConverterModule = module.default || module;
                outputSnippet.textContent = 'Module loaded. Converting...';
            }

            let generatedSnippet = "";

            // --- REAL CONVERSION LOGIC USING curlconverter ---
            if (targetLang === 'python') {
                generatedSnippet = curlConverterModule.toPython(curlInput);
                generatedSnippet = `# Generated by Snippet Genie\n# Target: Python Requests (Client-Side - Credit-Free)\n\n` + generatedSnippet;
            
            } else if (targetLang === 'nodejs') {
                 // Engagement message for future feature
                 generatedSnippet = `// ✨ Node.js Support Coming Soon! ✨\n// This feature is currently under active development and will be released next week!\n// For now, please enjoy the fast and accurate Python conversion.`;
            
            } else if (targetLang === 'go') {
                 // Engagement message for future feature
                 generatedSnippet = `// Go Support Coming Soon!\n// We prioritize Node.js, but Go support will follow shortly after.\n// Please check back soon!`;
            } else {
                 generatedSnippet = `Error: Unsupported language selected.`;
            }
            
            outputSnippet.textContent = generatedSnippet;

        } catch (error) {
            // This catches errors like malformed cURL input
            console.error("Client-side Conversion Error:", error);
            outputSnippet.textContent = `Error: Could not parse the cURL command. Check syntax. Details: ${error.message}`;
            alert(`Error during conversion: ${error.message}`);
        } finally {
             // Always hide the loading indicator
             loadingIndicator.style.display = 'none';
        }
    });

    // --- Copy Button Logic ---
    copyButton.addEventListener('click', () => {
        const textToCopy = outputSnippet.textContent;
        navigator.clipboard.writeText(textToCopy).then(() => {
            copyButton.textContent = 'Copied!';
            setTimeout(() => {
                copyButton.textContent = 'Copy Code';
            }, 2000);
        }).catch(err => {
            console.error('Could not copy text: ', err);
            alert('Failed to copy text. Please copy manually.');
        });
    });
});